# src/app.py
#
# Streamlit demo app for phishing detection + MITRE mapping + XAI explanation.
#
# Features:
# - Paste email text into a text area
# - Classify as phishing or legitimate
# - Show phishing probability
# - Show MITRE ATT&CK mapping
# - Show top XAI features from xai_explainer.py
# - Display generated analysis figures if available
#
# Run from project root:
#   streamlit run src/app.py

import os
import sys
from pathlib import Path

import streamlit as st

# Ensure src/ is importable when Streamlit runs from project root
CURRENT_FILE = Path(__file__).resolve()
SRC_DIR = CURRENT_FILE.parent
PROJECT_ROOT = SRC_DIR.parent

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from mvp_baseline import load_model
from xai_explainer import explain_email
from attacker_sim import mitre_mapping


# ---------------- Paths ---------------- #

FIGURES_DIR = PROJECT_ROOT / "simulation_results" / "figures"


# ---------------- Page Config ---------------- #

st.set_page_config(
    page_title="Phishing Detection XAI Dashboard",
    page_icon="📧",
    layout="wide",
)


# ---------------- Cached Model Loader ---------------- #

@st.cache_resource
def get_model():
    """
    Load and cache the vectorizer and classifier.
    """
    return load_model()


# ---------------- Prediction Helper ---------------- #

def classify_email(vectorizer, clf, text: str, threshold: float = 0.5):
    """
    Classify a single email using a custom phishing probability threshold.
    """
    X = vectorizer.transform([text])
    proba = clf.predict_proba(X)[0]

    if 1 in clf.classes_:
        phishing_index = list(clf.classes_).index(1)
    else:
        phishing_index = 1

    phishing_prob = float(proba[phishing_index])
    pred_label = 1 if phishing_prob >= threshold else 0

    return pred_label, phishing_prob


# ---------------- Sidebar ---------------- #

st.sidebar.title("Settings")

threshold = st.sidebar.slider(
    "Classification Threshold",
    min_value=0.10,
    max_value=0.95,
    value=0.50,
    step=0.05,
)

num_features = st.sidebar.slider(
    "Number of XAI Features",
    min_value=3,
    max_value=15,
    value=10,
    step=1,
)

use_lime = st.sidebar.checkbox(
    "Use LIME if available",
    value=True,
)

show_figures = st.sidebar.checkbox(
    "Show experiment figures",
    value=True,
)


# ---------------- Header ---------------- #

st.title("Phishing Detection, MITRE Mapping, and XAI Dashboard")
st.write(
    "This interface allows a user to paste an email message, classify it as phishing or legitimate, "
    "inspect the phishing probability score, view the mapped MITRE ATT&CK phishing category, "
    "and examine the explanation features generated by the XAI module."
)


# ---------------- Main Input ---------------- #

default_email = (
    "URGENT: Your account may be closed soon. "
    "We have detected suspicious activity on your account. "
    "Please respond within 24 hours to avoid losing access. "
    "Click here to resolve this issue: http://secure-verification-example.com/login"
)

email_text = st.text_area(
    "Paste Email Text",
    value=default_email,
    height=220,
)

analyse_clicked = st.button("Analyse Email")


# ---------------- Main Analysis ---------------- #

if analyse_clicked:
    if not email_text.strip():
        st.warning("Please enter some email text first.")
    else:
        try:
            vectorizer, clf = get_model()

            pred_label, phishing_prob = classify_email(
                vectorizer,
                clf,
                email_text,
                threshold=threshold,
            )

            mitre_label = mitre_mapping(email_text)

            explanation = explain_email(
                email_text,
                num_features=num_features,
                threshold=threshold,
                use_lime=use_lime,
            )

            prediction_text = "Phishing" if pred_label == 1 else "Legitimate"

            col1, col2, col3 = st.columns(3)

            with col1:
                st.subheader("Prediction")
                if pred_label == 1:
                    st.error(prediction_text)
                else:
                    st.success(prediction_text)

            with col2:
                st.subheader("Phishing Probability")
                st.metric(label="P(phishing)", value=f"{phishing_prob:.3f}")

            with col3:
                st.subheader("MITRE ATT&CK Mapping")
                st.info(mitre_label)

            st.subheader("Explanation Method")
            st.write(explanation["method"])

            st.subheader("Top XAI Features")

            top_features = explanation.get("top_features", [])
            if top_features:
                for feature in top_features:
                    term = feature.get("term", "")
                    weight = feature.get("weight", 0.0)
                    st.write(f"**{term}**: {weight:+.4f}")
            else:
                st.write("No explanation features were available for this email.")

        except FileNotFoundError:
            st.error(
                "Saved model files were not found. Please run mvp_baseline.py first to train and save the model."
            )
        except Exception as e:
            st.error(f"An error occurred while analysing the email: {e}")


# ---------------- Figures Section ---------------- #

if show_figures:
    st.divider()
    st.header("Simulation Result Figures")

    figure_files = [
        ("Detection Rate by Threshold", FIGURES_DIR / "threshold_detection_rate.png"),
        ("Bypass Rate by Threshold", FIGURES_DIR / "threshold_bypass_rate.png"),
        ("F1 Score by Threshold", FIGURES_DIR / "threshold_f1_score.png"),
        ("Accuracy by Threshold", FIGURES_DIR / "threshold_accuracy.png"),
        ("Detection Rate by Attack Type", FIGURES_DIR / "attack_type_detection_rate.png"),
        ("Detection Rate by Rule Chain", FIGURES_DIR / "rule_chain_detection_rate.png"),
        ("Detection Rate by MITRE Technique", FIGURES_DIR / "mitre_detection_rate.png"),
    ]

    existing_figures = [(title, path) for title, path in figure_files if path.exists()]

    if not existing_figures:
        st.info(
            "No figures were found yet. Run analyse_simulation_results.py and visualise_results.py first "
            "to generate the experiment charts."
        )
    else:
        for title, fig_path in existing_figures:
            st.subheader(title)
            st.image(str(fig_path), use_container_width=True)